{% set name = "flake8-nb" %}
{% set version = "0.1.4" %}
{% set download_name = "flake8_nb" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ download_name }}/{{ download_name }}-{{ version }}.tar.gz"
  sha256: "8c9bf95440e63bf6665c002620d127892f0d4eee9bf275975252b938f62fd287"

build:
  number: 0
  noarch: python
  entry_points:
    - flake8_nb = flake8_nb.__main__:main
    - flake8-nb = flake8_nb.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
    - pytest-runner
  run:
    - flake8 >=3.0.0
    - ipython >=7.8.0
    - nbconvert >=5.6.0
    - python >=3.6
    - pytest-runner
    - setuptools


test:
  imports:
    - flake8_nb
    - flake8_nb.flake8_integration
    - flake8_nb.parsers
  source_files:
    - tests
  commands:
    - flake8_nb --help
    - flake8-nb --help
    - pytest tests
  requires:
    - pytest >=3

about:
  home: "https://github.com/s-weigand/flake8-nb"
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Flake8 based checking for jupyter notebooks"
  doc_url: "https://flake8-nb.readthedocs.io"
  dev_url: "https://github.com/s-weigand/flake8-nb"

extra:
  recipe-maintainers:
    - s-weigand
