{% set name = "flake8-nb" %}
{% set version = "0.5.1" %}
{% set download_name = "flake8_nb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ download_name }}/{{ download_name }}-{{ version }}.tar.gz
  sha256: c40ed8f4a86d29cd5195433b3beea146222a844c20a3c5a32830434386a25bb3

build:
  number: 0
  noarch: python
  entry_points:
    - flake8_nb = flake8_nb.__main__:main
    - flake8-nb = flake8_nb.__main__:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - flake8 >=3.8.0,<5.0.5
    - ipython >=7.8.0
    - nbconvert >=5.6.0
    - python >=3.7
    - setuptools


test:
  imports:
    - flake8_nb
    - flake8_nb.flake8_integration
    - flake8_nb.parsers
  source_files:
    - tests
  commands:
    - flake8_nb --help
    - flake8-nb --help
    - pytest tests
  requires:
    - pytest >=3

about:
  home: https://github.com/s-weigand/flake8-nb
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Flake8 based checking for jupyter notebooks
  doc_url: https://flake8-nb.readthedocs.io
  dev_url: https://github.com/s-weigand/flake8-nb

extra:
  recipe-maintainers:
    - s-weigand
